server {
    listen 80;
    server_name kingvcam.com www.kingvcam.com api.kingvcam.com admin.kingvcam.com gdnew.kingvcam.com gdapps.online gdnew.gdapps.online;
    location /.well-known/acme-challenge/ { root /var/www/certbot; }
    location / { return 301 https://$host$request_uri; }
}

server {
    listen 443 ssl;
    http2 on;
    server_name kingvcam.com www.kingvcam.com;
    ssl_certificate /etc/letsencrypt/live/kingvcam.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kingvcam.com/privkey.pem;
    location / { proxy_pass http://kingvcam-api-1:8000; include /etc/nginx/proxy_params; }
}
server {
    listen 443 ssl;
    http2 on;
    server_name api.kingvcam.com;
    ssl_certificate /etc/letsencrypt/live/kingvcam.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kingvcam.com/privkey.pem;
    location /api/ { proxy_pass http://kingvcam-api-1:8000; include /etc/nginx/proxy_params; }
    location / { return 404; }
}
server {
    listen 443 ssl;
    http2 on;
    server_name admin.kingvcam.com;
    ssl_certificate /etc/letsencrypt/live/kingvcam.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kingvcam.com/privkey.pem;
    location = / { return 302 /admin; }
    location /admin { proxy_pass http://kingvcam-api-1:8000; include /etc/nginx/proxy_params; }
    location /static/ { proxy_pass http://kingvcam-api-1:8000; include /etc/nginx/proxy_params; }
    location / { return 404; }
}
server {
    listen 443 ssl;
    http2 on;
    server_name gdnew.kingvcam.com;
    ssl_certificate /etc/letsencrypt/live/gdnew.kingvcam.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/gdnew.kingvcam.com/privkey.pem;
    location / { proxy_pass http://gdnew-api:8000; include /etc/nginx/proxy_params; }
}
server {
    listen 443 ssl;
    http2 on;
    server_name gdapps.online;
    ssl_certificate /etc/letsencrypt/live/gdapps.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/gdapps.online/privkey.pem;
    location / { return 302 https://gdnew.gdapps.online$request_uri; }
}
server {
    listen 443 ssl;
    http2 on;
    server_name gdnew.gdapps.online;
    ssl_certificate /etc/letsencrypt/live/gdapps.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/gdapps.online/privkey.pem;
    location / { proxy_pass http://gdnew-api:8000; include /etc/nginx/proxy_params; }
}
